# Generated by Django 3.1.7 on 2022-02-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_personal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='Email_Address',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='Profession',
            new_name='profession',
        ),
    ]
