# Generated by Django 3.1.7 on 2022-02-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_Image',
        ),
    ]
