# Generated by Django 3.1.7 on 2022-02-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_about_me_education_job_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_Me',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Job_Experience',
        ),
    ]
