# Generated by Django 3.1.7 on 2022-02-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_about_me_education_job_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_Experience',
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=40),
        ),
    ]
