# Generated by Django 3.1.7 on 2022-02-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_job_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
