# Generated by Django 3.1.7 on 2022-02-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_delete_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_social_media', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
