# Generated by Django 3.1.7 on 2022-02-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_Pic',
        ),
    ]
